### PR TITLE
Notify GitHub errors once

### LINKED ISSUE #926: Notify only once for tracker errors
When the tracker encounters a failure, it currently sends three notifications over email, making it needlessly noisy and harder to track. Only one should be sent.

For reference, we get in the case of #925:

1. `2022-09-01 00:41:38 [31merror[39m Could not create issue`
2. `2022-09-01 00:41:38 [31merror[39m HttpError: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}`
3. `2022-09-01 00:41:38 [31merror[39m 🤖 Could not create Github issue for Fix TIME - Privacy Policy`

### PR DESCRIPTION
**Pull request by martinratinaud**
Fixes #926

The use of `logger.error` implies the sending of an email to the administrators so we need to keep only once per error encountered.

Also add more granularity to errors to know exactly which error occured

### CODE REVIEW

File: src/tracker/index.js [hunk 1]
```diff
@@ -156,54 +143,56 @@ export default class Tracker {
...
+        try {
+          await this.octokit.rest.issues.update({ ...this.commonParams, issue_number: openedIssue.number, state: ISSUE_STATE_CLOSED }); // eslint-disable-line no-await-in-loop
+          await this.addCommentToIssue({ ...this.commonParams, issue_number: openedIssue.number, body: comment }); // eslint-disable-line no-await-in-loop
+          logger.info(`🤖 Github issue closed for ${title}: ${openedIssue.html_url}`);
+        } catch (e) {
+          logger.error(`🤖 Could not close Github issue ${openedIssue.html_url}. ${e.toString()}`);
+        }
+      }
+    } catch (e) {
+      logger.error(`🤖 Could not close Github issues for ${title}. ${e.toString()}`);
```
Comment (MattiSG) [inline src/tracker/index.js:195]:
```suggestion
      logger.error(`🤖 Could not close GitHub issue for ${title}: ${e}`);
```

File: src/tracker/index.js [hunk 2]
```diff
@@ -156,54 +143,56 @@ export default class Tracker {
...
+    try {
+      const openedIssues = await this.searchIssues({ ...this.commonParams, title, labels, state: ISSUE_STATE_OPEN });
+
+      for (const openedIssue of openedIssues) {
+        try {
+          await this.octokit.rest.issues.update({ ...this.commonParams, issue_number: openedIssue.number, state: ISSUE_STATE_CLOSED }); // eslint-disable-line no-await-in-loop
+          await this.addCommentToIssue({ ...this.commonParams, issue_number: openedIssue.number, body: comment }); // eslint-disable-line no-await-in-loop
+          logger.info(`🤖 Github issue closed for ${title}: ${openedIssue.html_url}`);
+        } catch (e) {
+          logger.error(`🤖 Could not close Github issue ${openedIssue.html_url}. ${e.toString()}`);
```
Comment (MattiSG) [inline src/tracker/index.js:191]:
```suggestion
          logger.error(`🤖 Could not close GitHub issue ${openedIssue.html_url}: ${e}`);
```

File: src/tracker/index.js [hunk 3]
```diff
@@ -156,54 +143,56 @@ export default class Tracker {
...
-      await this.addCommentToIssue({ ...this.commonParams, issue_number: openedIssue.number, body: comment }); // eslint-disable-line no-await-in-loop
-      logger.info(`🤖 Github issue closed for ${title}: ${openedIssue.html_url}`);
+    try {
+      const openedIssues = await this.searchIssues({ ...this.commonParams, title, labels, state: ISSUE_STATE_OPEN });
+
+      for (const openedIssue of openedIssues) {
+        try {
+          await this.octokit.rest.issues.update({ ...this.commonParams, issue_number: openedIssue.number, state: ISSUE_STATE_CLOSED }); // eslint-disable-line no-await-in-loop
+          await this.addCommentToIssue({ ...this.commonParams, issue_number: openedIssue.number, body: comment }); // eslint-disable-line no-await-in-loop
+          logger.info(`🤖 Github issue closed for ${title}: ${openedIssue.html_url}`);
```
Comment (MattiSG) [inline src/tracker/index.js:189]:
```suggestion
          logger.info(`🤖 GitHub issue closed for ${title}: ${openedIssue.html_url}`);
```

File: src/tracker/index.js [hunk 4]
```diff
@@ -156,54 +143,56 @@ export default class Tracker {
...
+            logger.error(`🤖 Could not update Github issue ${existingIssue.html_url}. ${e.toString()}`);
+          }
           break;
         }
       }
-
-      return existingIssues;
     } catch (e) {
-      logger.error('Could not create issue', e.toString());
+      logger.error(`🤖 Could not create Github issue for ${title}. ${e.toString()}`);
```
Comment (MattiSG) [inline src/tracker/index.js:177]:
```suggestion
      logger.error(`🤖 Could not create GitHub issue for ${title}: ${e}`);
```

File: src/tracker/index.js [hunk 5]
```diff
@@ -156,54 +143,56 @@ export default class Tracker {
...
+            });
+            await this.addCommentToIssue({
+              ...this.commonParams,
+              issue_number: existingIssue.number,
+              body: `${comment}\n${body}`,
+            });
+            /* eslint-enable no-await-in-loop */
+            logger.info(`🤖 Reopened automatically as an error occured for ${title}: ${existingIssue.html_url}`);
+          } catch (e) {
+            logger.error(`🤖 Could not update Github issue ${existingIssue.html_url}. ${e.toString()}`);
```
Comment (MattiSG) [inline src/tracker/index.js:171]:
```suggestion
            logger.error(`🤖 Could not update GitHub issue ${existingIssue.html_url}: ${e}`);
```

Comment (MattiSG) [inline src/tracker/index.js:171]:
```suggestion
            logger.error(`🤖 Could not update GitHub issue ${existingIssue.html_url}: ${e}`);
```

Comment (MattiSG) [inline src/tracker/index.js:171]:
```suggestion
            logger.error(`🤖 Could not update GitHub issue ${existingIssue.html_url}: ${e}`);
```

**Review by MattiSG — COMMENTED** [review]
Sorry, I don't have time to review the logic now.

**Review by Ndpnt — APPROVED** [review]
